; SPRITES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 6
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", HOME

; Start of tile array.
TileLabel::
DB $81,$FF,$7E,$C3,$7E,$BD,$66,$BD
DB $66,$BD,$7E,$BD,$7E,$C3,$81,$FF
DB $00,$3C,$7E,$00,$DB,$24,$FF,$24
DB $FF,$24,$FF,$00,$FF,$00,$FF,$00
DB $FC,$00,$FE,$00,$FA,$1D,$FE,$01
DB $FE,$01,$FA,$1D,$FE,$00,$FC,$00
DB $FF,$00,$FF,$00,$FF,$00,$FF,$24
DB $FF,$24,$DB,$24,$7E,$00,$00,$3C
DB $3F,$00,$7F,$00,$5F,$B8,$7F,$80
DB $7F,$80,$5F,$B8,$7F,$00,$3F,$00
DB $00,$00,$00,$00,$00,$00,$18,$18
DB $18,$18,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$24,$18,$18,$3C
DB $18,$3C,$24,$18,$00,$00,$00,$00

; End of SPRITES.Z80
